// <auto-generated />
using System;
using LiquidWork.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LiquidWork.Persistence.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20200402202540_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("LiquidWork.Core.Model.Concepto", b =>
                {
                    b.Property<int>("ConceptoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Cantidad")
                        .HasColumnType("float");

                    b.Property<int?>("LegajoNumeroLegajo")
                        .HasColumnType("int");

                    b.Property<int?>("LiquidacionId")
                        .HasColumnType("int");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("NombreConcepto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Precedencia")
                        .HasColumnType("int");

                    b.Property<int>("TipoConcepto")
                        .HasColumnType("int");

                    b.HasKey("ConceptoId");

                    b.HasIndex("LegajoNumeroLegajo");

                    b.HasIndex("LiquidacionId");

                    b.ToTable("Conceptos");
                });

            modelBuilder.Entity("LiquidWork.Core.Model.Legajo", b =>
                {
                    b.Property<int>("NumeroLegajo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<long>("CUIL")
                        .HasColumnType("bigint");

                    b.Property<string>("Categoria")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<DateTime>("FechaIngreso")
                        .HasColumnType("date");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("NumeroLegajo");

                    b.ToTable("Legajos");
                });

            modelBuilder.Entity("LiquidWork.Core.Model.Liquidacion", b =>
                {
                    b.Property<int>("LiquidacionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("LegajoNumeroLegajo")
                        .HasColumnType("int");

                    b.Property<decimal>("Neto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Periodo")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TotalDeducciones")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalNoRemunerativo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalRemunerativo")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("LiquidacionId");

                    b.HasIndex("LegajoNumeroLegajo");

                    b.ToTable("Liquidaciones");
                });

            modelBuilder.Entity("LiquidWork.Core.Model.Concepto", b =>
                {
                    b.HasOne("LiquidWork.Core.Model.Legajo", "Legajo")
                        .WithMany("ConceptosFijos")
                        .HasForeignKey("LegajoNumeroLegajo")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("LiquidWork.Core.Model.Liquidacion", "Liquidacion")
                        .WithMany("Conceptos")
                        .HasForeignKey("LiquidacionId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("LiquidWork.Core.Model.Liquidacion", b =>
                {
                    b.HasOne("LiquidWork.Core.Model.Legajo", "Legajo")
                        .WithMany("Liquidaciones")
                        .HasForeignKey("LegajoNumeroLegajo")
                        .OnDelete(DeleteBehavior.SetNull);
                });
#pragma warning restore 612, 618
        }
    }
}
